// 설문 데이터
export const ALL_OPTION_LISTS = {
  work: ['8시간 미만 근무할 경우', '8~12시간 사이에 근무할 경우', '12시간 이상 근무할 경우'],
  task: ['근무시간의 50% 미만일 경우', '근무시간의 50~80% 사이일 경우', '근무시간의 80% 이상일 경우'],
  sleep: ['6시간 이내인 경우', '6~8시간 사이인 경우', '8시간 이상인 경우'],
  availtime: ['평상 시와 동일 하거나 느리게 해도 될 만큼의 여유시간이 주어진 상황일 경우',
    '평상 시보다 25%이내로 빠르게 해야 하는 상황일 경우',
    '평상 시보다 25% 이상 빠르게 해야 하는 상황일 경우'],
  work_shift: ['9시~18시인 경우', '야간근무 심야조', '야간근무 비심야조'],
  eq_avail: ['업무에 필요한 장비의 가용성이 높은 경우', '업무에 필요한 장비의 가용성이 낮은 경우'],
  eq_appro: ['사용하는 작업도구의 적절성이 우수한 경우', '사용하는 작업도구의 적절성이 보통한 경우',
    '사용하는 작업도구의 적절성이 미흡한 경우'],
  eq_support: ['업무에 사용되는 컴퓨터지원시스템(운행정보시스템, 운행관리시스템, 업무용 소프트웨어 등)이 우수한 경우',
    '업무에 사용되는 컴퓨터지원시스템(운행정보시스템, 운행관리시스템, 업무용 소프트웨어 등)이 보통인 경우',
    '업무에 사용되는 컴퓨터지원시스템(운행정보시스템, 운행관리시스템, 업무용 소프트웨어 등)이 미흡한 경우'],
  eq_usability: ['업무에 필요한 장비의 사용성이 우수한 경우', '업무에 필요한 장비의 사용성이 보통인 경우',
    '업무에 필요한 장비의 사용성이 미흡한 경우'],
  eq_procedure: ['장비 사용 매뉴얼의 질이 우수한 경우', '장비 사용 매뉴얼의 질이 보통인 경우',
    '장비 사용 매뉴얼의 질이 미흡한 경우'],
  eq_connectivity: ['사용하는 장비가 타 기기와의 연계성이 우수한 경우', '사용하는 장비가 타 기기와의 연계성이 보통인 경우',
    '사용하는 장비가 타 기기와의 연계성이 미흡한 경우'],
  eq_maintenance: ['사용하는 장비가 매우 적절하게 유지보수 되는 경우', '사용하는 장비가 일반적으로 유지보수 되는 경우',
    '사용하는 장비가 미흡하게 유지보수 되는 경우'],
  pro_availability: ['직무를 수행하는 데 필요한 절차의 가용성(접근성)이 높은 경우',
    '직무를 수행하는 데 필요한 절차의 가용성(접근성)이 낮은 경우'],
  pro_complexity: ['직무를 수행하는 데 필요한 절차의 복잡성이 높은 경우',
    '직무를 수행하는 데 필요한 절차의 복잡성이 보통인 경우',
    '직무를 수행하는 데 필요한 절차의 복잡성이 낮은 경우'],
  pro_clarity: ['직무 절차서 내용의 명료성이 높은 경우', '직무 절차서 내용의 명료성이 보통인 경우',
    '직무 절차서 내용의 명료성이 낮은 경우'],
  pro_appropriateness: ['직무 절차서 내용이 매우 적절하게 업무에 도움이 되는 경우',
    '직무 절차서 내용이 전반적으로 적절하게 업무에 도움이 되는 경우',
    '직무 절차서 내용이 부적절하거나 미흡하게 제공되는 경우'],
  pro_consistency: ['직무 절차서 내용이 매우 일관되게 표현되어 있는 경우',
    '직무 절차서 내용이 전반적으로 일관되게 표현되어 있는 경우',
    '직무 절차서 내용의 일관성이 부족한 경우'],
  pro_traceability: ['직무 절차서 추적성이 높은 경우', '직무 절차서 추적성이 보통인 경우',
    '직무 절차서 추적성이 낮은 경우'],
  ex_appropriateness: ['교육/훈련 프로그램이 적절할 경우', '교육/훈련 프로그램에 개선할 필요가 있을 경우',
    '교육/훈련 프로그램이 적절하지 않을 경우'],
  ex_frequency: ['교육/훈련 주기(빈도)가 6개월 미만일 경우', '교육/훈련 주기(빈도)가 6~12개월 사이일 경우',
    '교육/훈련 주기(빈도)가 1~2년 사이일 경우'],
  ex_experience: ['해야 하는 일의 90% 이상을 경험한 경우', '해야 하는 일의 70~90%를 경험한 경우',
    '해야 하는 일의 30% 이상을 경험하지 못한 경우'],
  ex_evaluation: ['직무능력 평가 빈도가 6개월일 경우', '직무능력 평가 빈도가 1년일 경우',
    '직무능력 평가 빈도가 3년일 경우'],
  ex_system_proficiency: ['시스템 지식(원리적 지식)의 숙련도가 높은 경우',
    '시스템 지식(원리적 지식)의 숙련도가 보통인 경우',
    '시스템 지식(원리적 지식)의 숙련도가 낮은 경우'],
  ex_procedure_proficiency: ['절차적 지식의 숙련도가 높을 경우', '절차적 지식의 숙련도가 보통인 경우',
    '절차적 지식의 숙련도가 낮은 경우'],
  ex_equipment_proficiency: ['장비 사용 지식의 숙련도가 높을 경우', '장비 사용 지식의 숙련도가 보통인 경우',
    '장비 사용 지식의 숙련도가 낮은 경우'],
  commu_length: ['의사소통 메시지 길이가 짧을(단문) 경우', '의사소통 메시지 길이가 보통일(중문) 경우',
    '의사소통 메시지 길이가 길(복문) 경우 경우'],
  commu_equipment: ['의사소통을 하기 위한 장비/기기가 적절한 상태일 경우',
    '의사소통을 하기 위한 장비/기기가 보통 수준인 상태일 경우',
    '의사소통을 하기 위한 장비/기기가 부적절한 상태일 경우'],
  commu_term: ['의사소통을 하기 위해 전문용어를 항상 숙지할 필요가 있는 경우',
    '의사소통을 하기 위해 전문용어를 부분적으로 숙지할 필요가 있는 경우',
    '의사소통을 하기 위해 전문용어를 숙지할 필요가 없는 경우'],
  commu_protocol: ['의사소통 프로토콜이 매우 구체적일 경우', '의사소통 프로토콜이 일부만 구체적일 경우',
    '의사소통 프로토콜이 구체적이지 않을 경우'],
  commu_SW: ['의사소통자 간의 상황인식 공유가 잘 되어 있을 경우', '의사소통자 간의 상황인식 공유가 부분적으로 되어 있을 경우',
    '의사소통자 간의 상황인식 공유가 되지 않을 경우'],
  commu_team: ['팀/조직 의사소통 자율성이 높을 경우', '팀/조직 의사소통 자율성이 보통일 경우',
    '팀/조직 의사소통 자율성이 낮을 경우'],
  env_wind: ['풍속이 10m/s 미만인 경우', '풍속 10m/s 이상인 경우'],
  env_rain: ['비가 10mm/h(눈의 경우 1cm/h) 미만', '비가 10mm/s(눈의 경우 1cm/s) 이상'],
  env_out_humidity: ['실외 습도가 90% 이하인 경우', '실외 습도가 90% 이상인 경우'],
  env_out_temp: ['실외 온도가 35℃(체감 온도) 이하인 경우', '실외 온도가 35℃(체감 온도) 이상인 경우'],
  env_lightning: ['낙뢰가 발생할 경우'],
  env_fog: ['안개가 발생할 경우'],
  env_dust: ['황사로 인해 작업자가 확실히 사물을 볼 수 없는 경우', '황사로 인해 작업자가 숨 쉬기가 불편할 경우'],
  env_space: ['작업공간의 크기가 10m^3 이상인 경우', '작업공간의 크기가 10m^3 이하인 경우'],
  env_friction: ['바닥 (정지)마찰계수(SCOF)가 ≥ 0.63인 경우', '바닥 (정지)마찰계수(SCOF)가 < 0.63인 경우'],
  env_in_temp: ['실내 온도가 17℃ 이하인 경우', '실내 온도가 17~28℃인 경우', '실내 온도가 28℃ 이상인 경우'],
  env_in_humidity: ['실내 습도가 40% 이하인 경우', '실내 습도가 40~75%인 경우', '실내 습도가 75% 이상인 경우'],
  env_ventilation: ['통풍이 잘 될 경우', '통풍이 잘 되지 않을 경우'],
  env_noise: ['소음이 85dB 이하인 경우', '소음이 85~115dB인 경우', '소음이 115dB 이상인 경우'],
  env_visibility: ['보통작업을 수행할 정도의 조도가 형성된 경우', '정밀작업을 수행할 정도의 조도가 형성된 경우',
    '초정밀작업을 수행할 정도의 조도가 형성된 경우'],
  work_supervisor: ['작업 관리 및 감독이 적절하게 이루어진 경우', '작업 관리 및 감독이 불완전하게 이루어진 경우',
    '작업 관리 및 감독이 부적절하게 이루어진 경우'],
  work_plan: ['작업 계획이 적절하게 이루어진 경우', '작업 계획이 불완전하게 이루어진 경우',
    '작업 계획이 부적절하게 이루어진 경우'],
  work_process: ['작업절차 및 규정이 좋은 경우', '작업절차 및 규정이 보통인 경우', '작업절차 및 규정이 좋지 않은 경우'],
  work_role: ['역할 분담이 명확한 경우', '역할 분담이 모호한 경우', '역할 분담이 명확하지 않은 경우'],
  work_cooperation: ['작업자간 협업이 원활한 경우', '작업자간 협업이 제한적인 경우', '작업자간 협업이 원활하지 않은 경우'],
  com_clarity: ['의사결정이 필요한 상황에서 의사결정 목표가 명확할 경우',
    '의사결정이 필요한 상황에서 의사결정 목표가 명확하지 않을 경우'],
  com_alternative: ['의사결정 과정에서 선택할 수 있는 대안의 수가 2건 이하인 경우',
    '의사결정 과정에서 선택할 수 있는 대안의 수가 3~4건인 경우',
    '의사결정 과정에서 선택할 수 있는 대안의 수가 5건 이상인 경우'],
  com_judgment: ['올바른 의사결정을 위해 고려해야 하는 판단기준(예: 시간, 비용, 인력 등)의 수가 1개일 경우',
    '올바른 의사결정을 위해 고려해야 하는 판단기준(예: 시간, 비용, 인력 등)의 수가 2~3개일 경우',
    '올바른 의사결정을 위해 고려해야 하는 판단기준(예: 시간, 비용, 인력 등)의 수가 4개 이상일 경우'],
  com_number: ['동시에 처리되어야 하는 의사결정의 수가 1개일 경우',
    '동시에 처리되어야 하는 의사결정의 수가 2개일 경우',
    '동시에 처리되어야 하는 의사결정의 수가 3개 이상일 경우'],
  com_observation: ['업무수행 및 의사결정을 위해 관측 되어야 하는 정보의 양이 3개 이하일 경우',
    '업무수행 및 의사결정을 위해 관측 되어야 하는 정보의 양이 4~6개일 경우',
    '업무수행 및 의사결정을 위해 관측 되어야 하는 정보의 양이 7개 이상일 경우'],
  com_inference: ['업무수행 및 의사결정을 위해 파악하고 있어야 하나 직접적으로 관측되지 않아 관측된 정보를 이용해 추론해야 하는 정보의 양이 1개인 경우',
    '업무수행 및 의사결정을 위해 파악하고 있어야 하나 직접적으로 관측되지 않아 관측된 정보를 이용해 추론해야 하는 정보의 양이 2~4개인 경우',
    '업무수행 및 의사결정을 위해 파악하고 있어야 하나 직접적으로 관측되지 않아 관측된 정보를 이용해 추론해야 하는 정보의 양이 5개 이상인 경우'],
  com_uncertainty: ['업무수행 및 의사결정을 위해 필요한 정보의 불확실성이 높은 경우',
    '업무수행 및 의사결정을 위해 필요한 정보의 불확실성이 높지 않은 경우'],
};

export const SURVEY_DATA = [
  {
    id: 1,
    psf: "피로도",
    text: "1. 다음의 조건이라고 가정했을 때, 귀하가 느끼는 작업 부하 수준은 어느 정도에 해당합니까?",
    condition_keys: ['work', 'task', 'sleep', 'availtime', 'work_shift'],
    condition_labels: {
      work: '근무시간',
      task: '작업시간',
      sleep: '수면시간',
      availtime: '작업 허용 시간',
      work_shift: '근무시간대',
    },
    options: ["보통", "나쁨", "매우나쁨"],
    condition_columns: 1,
    condition_descriptions: {},
  },
  {
    id: 2,
    psf: "장비/기술",
    text: "2. 다음의 조건이라고 가정했을 때, 귀하가 느끼는 장비의 품질(성능, 상태, 적합도 등)수준은 어느 정도입니까?",
    condition_keys: ['eq_avail', 'eq_appro', 'eq_support', 'eq_usability', 'eq_procedure', 'eq_connectivity', 'eq_maintenance'],
    condition_labels: {
      eq_avail: '장비 가용성(접근성)',
      eq_appro: '작업 도구의 적절성',
      eq_support: '컴퓨터 지원 시스템의 적절성',
      eq_usability: '장비의 사용성',
      eq_procedure: '장비 사용 매뉴얼의 질',
      eq_connectivity: '타 기기와의 연계성',
      eq_maintenance: '유지보수의 적절성',
    },
    options: ["좋음", "보통", "나쁨"],
    condition_columns: 1,
    condition_descriptions: {},
  },
  {
    id: 3,
    psf: "절차/문서",
    text: "3. 다음의 조건이라고 가정했을 때, 귀하가 느끼는 절차서의 품질 수준은 어느 정도입니까?",
    condition_keys: ['pro_availability', 'pro_complexity', 'pro_clarity', 'pro_appropriateness', 'pro_consistency', 'pro_traceability'],
    condition_labels: {
      pro_availability: '(직무)절차의 유무(가용성)',
      pro_complexity: '(직무)절차의 복잡성',
      pro_clarity: '(직무)절차의 명료성(구체성)',
      pro_appropriateness: '(직무)절차의 적절성(완전성 포함)',
      pro_consistency: '(직무)절차의 일관성',
      pro_traceability: '(직무)절차의 추적성',
    },
    options: ["좋음", "보통", "나쁨"],
    condition_columns: 1,
    condition_descriptions: {},
  },
  {
    id: 4,
    psf: "교육/훈련",
    text: "4. 다음의 조건이라고 가정했을 때, 귀하가 느끼는 교육/훈련 성과 및 수준은 어느 정도입니까?",
    condition_keys: ['ex_appropriateness', 'ex_frequency', 'ex_experience', 'ex_evaluation', 'ex_system_proficiency', 'ex_procedure_proficiency', 'ex_equipment_proficiency'],
    condition_labels: {
      ex_appropriateness: '교육/훈련 프로그램 적절성',
      ex_frequency: '교육 주기(빈도)',
      ex_experience: '상황에 대한 경험 정도(자주 또는 드물게 겪는지)',
      ex_evaluation: '직무능력 평가 빈도',
      ex_system_proficiency: '시스템 지식(원리적 지식)의 숙련도',
      ex_procedure_proficiency: '절차적 지식의 숙련도',
      ex_equipment_proficiency: '장비 사용 지식의 숙련도',
    },
    options: ["좋음", "보통", "나쁨"],
    condition_columns: 1,
    condition_descriptions: {},
  },
  {
    id: 5,
    psf: "의사소통",
    text: "5. 다음의 조건이라고 가정했을 때, 귀하가 느끼는 의사소통은 어느 정도입니까?",
    condition_keys: ['commu_length', 'commu_equipment', 'commu_term', 'commu_protocol', 'commu_SW', 'commu_team'],
    condition_labels: {
      commu_length: '의사소통 메시지의 길이',
      commu_equipment: '의사소통을 위한 장비/기기의 적절성',
      commu_term: '의사소통을 위한 전문용어 숙지 필요성',
      commu_protocol: '의사소통 프로토콜의 구체성',
      commu_SW: '의사소통자 간 상황인식 공유 정도',
      commu_team: '팀/조직 의사소통 자율성',
    },
    options: ["보통", "나쁨"],
    condition_columns: 1,
    condition_descriptions: {},
  },
  {
    id: 6,
    psf: "환경요인",
    text: "6. 다음의 조건이라고 가정했을 때, 귀하가 느끼는 업무 수행 환경은 어느 정도입니까?",
    condition_keys: ['env_wind', 'env_rain', 'env_out_humidity', 'env_out_temp', 'env_lightning', 'env_fog', 'env_dust', 'env_space', 'env_friction', 'env_in_temp', 'env_in_humidity', 'env_ventilation', 'env_noise', 'env_visibility'],
    condition_labels: {
      env_wind: '풍속',
      env_rain: '비',
      env_out_humidity: '실외 습도',
      env_out_temp: '실외 온도',
      env_lightning: '낙뢰',
      env_fog: '안개',
      env_dust: '황사',
      env_space: '작업공간 크기',
      env_friction: '마찰계수',
      env_in_temp: '실내 온도',
      env_in_humidity: '실내 습도',
      env_ventilation: '통풍',
      env_noise: '소음',
      env_visibility: '업무공간 가시성',
    },
    options: ["보통", "나쁨"],
    condition_columns: 1,
    condition_descriptions: {},
  },
  {
    id: 7,
    psf: "조직/관리",
    text: "7. 다음의 조건이라고 가정했을 때, 귀하가 느끼는 작업 절차는 어느 정도입니까?",
    condition_keys: ['work_supervisor', 'work_plan', 'work_process', 'work_role', 'work_cooperation'],
    condition_labels: {
      work_supervisor: '작업 관리 및 감독 적절성',
      work_plan: '작업 계획 적절성',
      work_process: '작업절차 및 규정',
      work_role: '역할 분담 명료화',
      work_cooperation: '작업자간 협업 정도',
    },
    options: ["좋음", "보통", "나쁨"],
    condition_columns: 1,
    condition_descriptions: {},
  },
  {
    id: 8,
    psf: "직무 복잡도",
    text: "8. 다음의 조건이라고 가정했을 때, 귀하가 느끼는 직무 복잡도는 어느 정도입니까?",
    condition_keys: ['com_clarity', 'com_alternative', 'com_judgment', 'com_number', 'com_observation', 'com_inference', 'com_uncertainty'],
    condition_labels: {
      com_clarity: '의사결정 목표의 명확성',
      com_alternative: '의사결정 대안의 수',
      com_judgment: '의사결정 판단 기준의 수',
      com_number: '(동시에 처리 되어야 하는)의사결정 수',
      com_observation: '관측되는 정보의 양',
      com_inference: '(관측이 안되서)추론해야하는 정보의 양',
      com_uncertainty: '정보의 불확실성',
    },
    options: ["보통", "약간 높음", "매우 높음"],
    condition_columns: 1,
    condition_descriptions: {},
  },
];
